# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ndoejsappservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://nodejsappservice.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_b164cea1410640f984c692f4ab881e9d }}
          password: ${{ secrets.AzureAppService_ContainerPassword_58885d1c1ad042bc8433295aa0f2f154 }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nodejsappservice.azurecr.io/nodejsappservice:latest
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=registry,ref=nodejsappservice.azurecr.io/nodejsappservice:buildcache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache,new=true
            type=registry,ref=nodejsappservice.azurecr.io/nodejsappservice:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ndoejsappservice'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0ac3ea140de441f837fd5fe1074c220 }}
          images: 'nodejsappservice.azurecr.io/nodejsappservice:latest'
